Rhizome-Conifer/conifer

- rec/wrrecorder/anonchecker.py
- webrecorder/static/recordings.js
- webrecorder/templates/base_bootstrap.html
- webrecorder/templates/breadcrumbs.html
- webrecorder/templates/index.html
- webrecorder/templates/user_management_links.html
- webrecorder/test/test_anon_content.py
- webrecorder/test/test_colls_api.py
- webrecorder/test/test_recs_api.py
- webrecorder/test/testutils.py
- webrecorder/webrecorder/appcontroller.py
- webrecorder/webrecorder/basecontroller.py
- webrecorder/webrecorder/collscontroller.py
- webrecorder/webrecorder/contentcontroller.py
- webrecorder/webrecorder/recscontroller.py
- webrecorder/webrecorder/redisman.py
- webrecorder/webrecorder/session.py
- webrecorder/webrecorder/usercontroller.py
Use consistent `user/coll/rec` paths for temporary collections, remove redundant code for 'anonymous'
> Replace 'anonymous' collection with temporary user and 'temp' collection

- webrecorder/static/recordings.js
- webrecorder/static/styles.css
- webrecorder/templates/index.html
- webrecorder/templates/recordings/homepage_recorder.html
- webrecorder/templates/recordings/new.html
- webrecorder/templates/register.html
- webrecorder/templates/temporary_collection_info.html
- webrecorder/test/test_all_register_migrate.py
- webrecorder/test/test_login.py
- webrecorder/webrecorder/logincontroller.py
- webrecorder/webrecorder/redisman.py
- wr.yaml
recording name: defaults to a name including current timestamp, both on home page and new rec screen
when logged in, allow selecting a collection
login: if not migrating a collection, automatically create 'Default Collection' so that a collection always exists
experiment: redirect to home page instead of user page after logging in so user can start recording right away
into newly created collection.
login ops: disallow register/login/forgot/validate ops if already logged
default collection: id, title, desc defined in wr.yaml
closes #81
> home page: allow specifying a recording name

- rec/wrrecorder/tempchecker.py
- webrecorder/.coveragerc
- webrecorder/Dockerfile
- webrecorder/requirements.txt
- webrecorder/test/test_invites_config.yaml
- webrecorder/test/test_no_invites_config.yaml
- webrecorder/test/testutils.py
- webrecorder/webrecorder/appcontroller.py
- webrecorder/webrecorder/cookieguard.py
- webrecorder/webrecorder/session.py
- webrecorder/webrecorder/webreccork.py
- wr.env
- wr.yaml
- anon/temp users get a fixed amount of time from session creation, shown by timer, does not refresh
- logged in users get a fixed session which extends automatically if less than threshold remaining
- todo: remember me option (or longer logged in sessions?)
> sessions: no more beaker! use custom sessions to support:

- .gitignore
- webrecorder/uwsgi.ini
- webrecorder/webrecorder/redisman.py
- wr_sample.env
Adds `MAILING_LIST` flag to the `wr.env` config to enable 3rd party mailing list support. 
`MAILING_LIST_ENDPOINT`, `MAILING_LIST_KEY`, `MAILING_LIST_PAYLOAD` are configurable.
> Mailing list support

- webrecorder/webrecorder/downloadcontroller.py
- wr.yaml
support both chunk-encoding and normal non-chunked download where the content-length is computed for the entire WARC
via the 'download_chunked_encoded' config setting (defaults to true)
> downloadcontroller: fix download of individual recording WARCs #234

- webrecorder/static/recordings.js
- webrecorder/templates/content_error.html
- webrecorder/test/test_all_temp_content.py
- webrecorder/webrecorder/contentcontroller.py
Add `/$patch/` url to redirect to a new patch, unify redirects, enable 'Record this page' on temp collections, (check `can_write()` instead of `can_admin()`)
> 'Record this page' link fix for cross-domain config

- webrecorder/webrecorder/static/newrecording.js
Edit collection dropdown in place so that the url and recording session title aren't lost.
h/t @patshiu
> HP recorder: add new collection without refreshing page

- webrecorder/webrecorder/config/wr.yaml
- webrecorder/webrecorder/config/wr_sample.env
- webrecorder/webrecorder/contentcontroller.py
- webrecorder/webrecorder/rec/webrecrecorder.py
- webrecorder/webrecorder/redisman.py
- webrecorder/webrecorder/templates/error.html
can record upto X bytes over Y hours.
limiting done by ip (using x-real-ip header if available) #343
> add anonymous rate-limiting support: if enabled via wr.env, users

- webrecorder/test/test_rec.py
- webrecorder/webrecorder/basecontroller.py
- webrecorder/webrecorder/config/wr.yaml
- webrecorder/webrecorder/contentcontroller.py
- webrecorder/webrecorder/load/main.py
- webrecorder/webrecorder/rec/webrecrecorder.py
- webrecorder/webrecorder/static/recordings.js
- webrecorder/webrecorder/utils.py
- create new patch recording in recorder only if needed (eg. loading from a secondary source)
- add 'extract_only' mode that only extracts, no patching
- use 'sources' and 'inv_sources' to specify secondary sources to patch
- utils: move sanitize_title/sanitize_tag to utils
- ui: fix typo, missing extractPage function
- config: remove unused key
> extract + patch mode work (#351):

- .gitignore
- webrecorder/webrecorder/templates/branding.html
- webrecorder/webrecorder/templates/error.html
- webrecorder/webrecorder/templates/frame_insert.html
- webrecorder/webrecorder/templates/login_modal.html
- webrecorder/webrecorder/templates/paging_display.html
- webrecorder/webrecorder/templates/proxy_error.html
- webrecorder/webrecorder/templates/register.html
- webrecorder/webrecorder/templates/reporterror.html
- webrecorder/webrecorder/templates/reset.html
- webrecorder/webrecorder/templates/upload_modal.html
This pull updates some of the templates to use `{{ metadata.product }}` and `{{ get_app_host() }}` in place of `Webrecorder` and `webrecorder.io`, the same way other templates already do.
Caveats:
- I didn’t mess with FAQ, email templates, or terms of use, which all seem trickier to white label.
- I deleted branding.html, which I think is unused. Let me know if that’s wrong and I’ll undo.
> Branding tweaks

- webrecorder/test/test_rec.py
- webrecorder/webrecorder/contentcontroller.py
- webrecorder/webrecorder/rec/storagecommitter.py
- webrecorder/webrecorder/rec/webrecrecorder.py
- Fixes for issues caused by on-demand recording creation in recorder. Instead, create patch recording in app always.
- Use `no_dupe=True` to avoid creating duplicates instead of has_recording check
- StorageCommitter fix: skip temp user dirs right away
- ContentController:  add back `/$record/` route
> Recorder fixes

- webrecorder/test/test_all_temp_content.py
- webrecorder/webrecorder/contentcontroller.py
- Fixes the use of special characters in the recording name e.g. `/`
- Adds test for using special characters in recording title
> Add path matching to recording title url filter

- webrecorder/test/test_extract.py
- webrecorder/webrecorder/contentcontroller.py
- patch recording uses recording title, not id
- ensure patch recording created same time as extract recording, either before redirect or on first use
tests: add extract and extract only basic tests, ensure proper recordings are created after extracting
> extract + patch naming:

- docker-compose.yml
- nginx/nginx.conf
- remove volume only 'data' container, mount ./data directly
- remove 'volumes_from', mount volumes directly
- nginx: shepherd, just route /static/browsers -> shepherd/static/ instead of mounting another volume
> docker-compose cleanup:

- webrecorder/test/test_all_register_migrate.py
- webrecorder/test/test_colls_api.py
- webrecorder/webrecorder/collscontroller.py
- webrecorder/webrecorder/contentcontroller.py
- webrecorder/webrecorder/redisman.py
- split _check_access() into check read and check write access
- check read access returns 'public' if read access is public, otherwise true/false
- for collection replay, add 'cache-control: private' to avoid cacheing at frontend, unless read access is 'public'
- anon user: better ensure access only to 'temp' collection, restrict adding duplicate 'temp' collections
- tests: update tests to check for 'cache-control: private' and no duplicate temp collections
- when adding auto-duplicate colls, ensure admin access for new collection to be added
> cache/access check improvements:

- .travis.yml
Build with pyisntaller on OSX 10.10 to support >=10.10
> travis-ci: use OSX 10.10 Build

- webrecorder/test/test_lists_api.py
- webrecorder/webrecorder/contentcontroller.py
Simply list replay endpoint, eg. `/user/coll/list/<list_id>/mp_/<url>`
- add tests to ensure top url contains `/user/coll/list/<list_id>/<url>`
- (note that url does not have to be bookmark in list)
> list replay: add /user/coll/list/<list_id>/... as content replay route

- webrecorder/test/test_api_user_login.py
- webrecorder/test/test_lists_api.py
- webrecorder/test/test_lists_multi_user.py
- webrecorder/webrecorder/collscontroller.py
- webrecorder/webrecorder/listscontroller.py
- webrecorder/webrecorder/models/collection.py
- webrecorder/webrecorder/models/list_bookmarks.py
- webrecorder/webrecorder/models/user.py
- webrecorder/webrecorder/usercontroller.py
Various API tweaks:
- `include_lists` and `include_recordings` query params for `/api/v1/collections` endpoint
- `/api/v1/users/<user>` endpoint does not include recordings or lists
- `/api/v1/users/<user>` endpoint supported for current temp user (and only for current user or admin)
- `/api/v1/logout` returns JSON instead of redirecting
- `/api/v1/list/<list_id>/bulk_bookmarks` POST endpoint to add bookmarks in bulk (as a JSON list)
- update tests for API changes
> API Tweaks: Optional lists and recordings, bulk list add

- webrecorder/test/test_auto_login.py
- webrecorder/test/test_lists_anon_user.py
- webrecorder/test/test_lists_multi_user.py
- webrecorder/test/test_recs_api.py
- webrecorder/test/test_upload.py
- webrecorder/test/testutils.py
- webrecorder/webrecorder/models/base.py
- webrecorder/webrecorder/models/list_bookmarks.py
- webrecorder/webrecorder/models/pages.py
- webrecorder/webrecorder/utils.py
- for lists and bookmarks, use shorter, 8-char uuid
- test for dupes when allocating new uuid
- for pages, use rec id + browser in hash key to allow dupe pages and different browsers
> uuid fixes: 

- README.md
Clarify instructions for launching webrecorder locally by formalizing launch step and clarifying what is needed for port.
>  define <DOCKER HOST> final step for more clarity

- webrecorder/test/test_upload.py
- webrecorder/webrecorder/downloadcontroller.py
- webrecorder/webrecorder/models/base.py
- webrecorder/webrecorder/models/importer.py
- ensure collection and recording timestamps are set to the original value
- add update_ts flag to set_prop() to avoid changing updated_at when setting prop
- ensure recording 'recorded_at' property exported/imported, convert to iso on serialization
> upload timestamps:

- frontend/src/helpers/ApiClient.js
- frontend/src/server.js
- webrecorder/webrecorder/session.py
api session: ensure redis key is extended to duration if cookie duration is extended, even if no change to session data
frontend: ensure 'Set-Cookie' header, if set, is passed from api back to browser
> session fix:

- webrecorder/test/test_pending.py
- webrecorder/test/test_storage_commit.py
- webrecorder/test/test_upload.py
- webrecorder/webrecorder/rec/tempchecker.py
- webrecorder/webrecorder/rec/webrecrecorder.py
- ensure 'pending_size' and 'pending_count' only updated if recording session still exists/is open
- recorderapp: move create_write_buffer() to writer, ensure recording open key expiry is extended while continuing to read data
- tests: add pending_size/count tests to ensure proper update, update for concurrent writers, at 0 after all requests done, and no further update if recording session deleted while recording
- tests: update sleep wait timeouts on storage and upload tests to avoid appveyor failures?
> pending count improvements:

- webrecorder/test/test_anon_workflow.py
- webrecorder/test/test_extract.py
- webrecorder/test/test_patch.py
- webrecorder/test/test_upload.py
- webrecorder/webrecorder/collscontroller.py
- webrecorder/webrecorder/models/collection.py
- webrecorder/webrecorder/models/recording.py
- webrecorder/webrecorder/models/stats.py
- webrecorder/webrecorder/models/user.py
- webrecorder/webrecorder/recscontroller.py
- webrecorder/webrecorder/uploadcontroller.py
- all capture (record + patch + extract), logged in and anon
- delete logged in and anon
- patch logged in and anon
- download (size and counts) logged in and anon
- upload size and count
- remote browser count
- remote archive count
delete api:
- return 400 if delete failed (eg. already deleted)
- if single file delete failed, still delete, return 200, but add file to retry queue
> stats improvements (per day):

- webrecorder/test/test_anon_workflow.py
- webrecorder/test/test_lists_anon_user.py
- webrecorder/test/test_lists_multi_user.py
- webrecorder/test/test_login_migrate.py
- webrecorder/test/test_register_migrate.py
- webrecorder/webrecorder/contentcontroller.py
- webrecorder/webrecorder/models/list_bookmarks.py
- webrecorder/webrecorder/models/stats.py
Additional stats to track:
- bookmark add, modify, delete
- count of temp collection added to account
- replay traffic: count WARC record length, bucket by day, temp vs logged in users
- requires latest pywb 2.0.4 build for _add_custom_params() change
> More stats

- frontend/src/redux/modules/auth.js
- webrecorder/test/test_api_user_login.py
- webrecorder/test/test_app_content_domain.py
- webrecorder/test/test_lists_multi_user.py
- webrecorder/test/test_login_migrate.py
- webrecorder/test/test_register_migrate.py
- webrecorder/test/test_upload.py
- webrecorder/webrecorder/basecontroller.py
- webrecorder/webrecorder/contentcontroller.py
- webrecorder/webrecorder/models/usermanager.py
- webrecorder/webrecorder/usercontroller.py
- when logging in, out or deleting user, redirect to <content host>/_clear_session
to clear content host cookie
- convert /api/v1/logout from get to post for additional security
- tests: add tests for clear session redirect, _clear_session call, updated to post to login
- frontend: switch to using post for logout
> clear content session when in app/content domain mode:

- webrecorder/test/test_app_content_domain.py
- webrecorder/test/test_login_migrate.py
- webrecorder/test/test_register_migrate.py
- webrecorder/webrecorder/contentcontroller.py
- webrecorder/webrecorder/models/stats.py
- webrecorder/webrecorder/usercontroller.py
- Add new stat for size of temp data moved to user account
- ~Add frame-ancestors to csp policy~ Blocks embedding WR, so had to remove
- Remove: redirect to _clear_session on login/logout/delete (breaks IE11, doesn't actually clear the session w/o extra credentials headers!)
> Stats and csp

- webrecorder/test/test_bugreport.py
- webrecorder/test/test_register_migrate.py
- webrecorder/webrecorder/bugreportcontroller.py
- webrecorder/webrecorder/collscontroller.py
- webrecorder/webrecorder/gh_reporter.py
- webrecorder/webrecorder/models/base.py
- webrecorder/webrecorder/models/usermanager.py
- add support for ui reporting via /api/v1/report/ui
- Add simplified bug report template with 'ui-report' issue, '[UI Report]' in title
- usermanager: ensure get_user_email() returns empty string for non-existent user
collection api fix:
- don't allow renaming collection to empty slug/name, return 400 'invalid_coll_name' if slug is empty
> bugreporter improvement:

- webrecorder/webrecorder/maincontroller.py
- webrecorder/webrecorder/standalone/assetsutils.py
- webrecorder/webrecorder/standalone/hooks/hook-webrecorder.py
Ensure backend `static/bundle` assets are generated automatically on launch, primarily used for `pywb.js` and `proxy.js`
> Auto Gen Backend Assets

- webrecorder/test/test_colls_api.py
- webrecorder/test/test_external.py
- webrecorder/webrecorder/basecontroller.py
- webrecorder/webrecorder/collscontroller.py
- webrecorder/webrecorder/models/collection.py
- if 'ALLOW_EXTERNAL' env var is set to truthy value, allow temporary, external collections
- external collections created with 'external' flag on /api/v1/collections
- external collections do not have recordings and do not delete data
- warc mapping and cdx for external collections can be added with PUT /api/v1/collection/<name>/warc and PUT /api/v1/collection/<name>/cdx
- warc mapping must be accessible to webrecorder, eg. local mount, external http:// url
- external collections can be added to temp users only and can have any name, not just 'temp'
- tests: add test for external collection replay, verify only available if ALLOW_EXTERNAL=1
> Add external collection api:

- webrecorder/test/test_dat_api.py
- webrecorder/webrecorder/collscontroller.py
- webrecorder/webrecorder/models/base.py
- webrecorder/webrecorder/models/collection.py
- webrecorder/webrecorder/models/datshare.py
- webrecorder/webrecorder/models/importer.py
- webrecorder/webrecorder/standalone/webrecorder_player.py
- add collection import_serialized() which rebuilds collection from root dir and metadata produced by serialize()
- add player --coll-dir option to initialize collection from serialized metadata.yaml
- dat: metadata.yaml serialization writes pages per recording, not per collection (to match warc download serialization)
- dat share: add always_update=true option to force update even if no changes detected
> collection: import from serialized metadata prototype:

- webrecorder/test/test_dat_api.py
- webrecorder/webrecorder/collscontroller.py
- webrecorder/webrecorder/models/collection.py
- webrecorder/webrecorder/models/datshare.py
- rename dat_committed_at -> dat_updated_at
- add 'dat_share' boolean to indicate if dat sharing is enabled
- unshare toggles dat_share, does not delete dat  key
- serialize: convert dat_updated_at to date, dat_share to boolean
> dat api work: allow dat access only for beta-archivist users

- rebuild.sh
- recreate.sh
- webrecorder/migration_scripts/migrate4.0.py
- webrecorder/webrecorder/config/wr_sample.env
- webrecorder/webrecorder/models/recording.py
- support full import of all users
- disable per-recording list by default
- skip recording or collection if missing: id, created_at, updated_at
- print errors for missing created_at, updated_at
- skip non-s3 files (for now)
- don't migrate if user already exists
- remove empty user dir after done with user migration
- set description for auto-generated list
- recompute size for recordings, collections, user (if updating all collections)
- change properties at end to avoid setting the updated_at timestamp
- add update_ts property to set_prop() to avoid setting the updated_at timestamp, (if False)
- add s3 copy method, support parallel migration with migrate:q
- copy registration, usage keys
- add bookmarks in ascending time order
- change get_user() -> make_user(), default ts to '' if …
> Updated Migration Script for Webrecorder 3.x -> 4.x migration

- webrecorder/test/test_create_new_api.py
- webrecorder/test/test_external.py
- webrecorder/test/test_player_proxy.py
- webrecorder/test/test_ws.py
- webrecorder/test/testutils.py
- webrecorder/webrecorder/contentcontroller.py
- webrecorder/webrecorder/maincontroller.py
- webrecorder/webrecorder/session.py
- webrecorder/webrecorder/usercontroller.py
Various API usage improvements:
* API endpoint for creating new temp user session`/api/v1/auth/anon_user` readded, curr_user only returns user, does not initialize new session.
* Support for redirecting to custom error page in content view if `CONTENT_ERROR_REDIRECT` is set. Redirect happens for both replay not found and any generic error.
* Cookie handoff improvement, `__set_session` now accepts the `cookie=` param instead of internal `id=` param for better use with external services that are handing off the cookie.
* Test updates for new api, custom error page, and extra test for WS init in player proxy.
> API endpoint improvements, custom error page support

- frontend/src/containers/App/App.js
- frontend/src/redux/modules/auth.js
- webrecorder/webrecorder/session.py
- If request isn't a logged in or active temp user, call `/api/v1/auth/anon_user` to add a cookie explicitly.
- Add cookie check in session.py
> Temp user session fix

- frontend/src/helpers/ApiClient.js
When server-side session cookie is passed from api to browser, ensure the `Secure` flag is also added in running via https to be consistent with cookies set directly via api.
> Ensure server-side render cookie has "Secure" flag

- webrecorder/test/test_app_content_domain.py
- webrecorder/webrecorder/basecontroller.py
- webrecorder/webrecorder/contentcontroller.py
- webrecorder/webrecorder/maincontroller.py
- webrecorder/webrecorder/session.py
It is possible (not entirely clear why!) for app cookie and content cookie to become out of sync, eg. a new session is set on the app cookie, but content cookie is stale.
Currently, this results in a 404 when loading any content and is difficult to recover from.
This fixes the issue by attempting to reset the content cookie on certain types of 404s.
If a content 404 is found:
- detect if `Referer` is the app request to same page to determine if its a top-level page, and check that redir lock is not set.
- if the referrer matches, redirect to `app-host/_set_session`, including `content_cookie` as extra param. set skip lock for 10 seconds to avoid redirect loop.
- if `/_set_session` detects that `content_cookie` is different from current session, continue session reset. otherwise, redirect …
> Detect and reset content cookie if it out of sync with app cookie

- webrecorder/test/test_auto_login.py
- webrecorder/test/test_create_new_api.py
- webrecorder/test/test_external.py
- webrecorder/test/test_pending.py
- webrecorder/test/test_storage_commit.py
- webrecorder/test/test_ws.py
- webrecorder/test/testutils.py
- webrecorder/webrecorder/session.py
Fix `Session.set_anon` to explicitly set the temp user key `t:<temp user>` to ensure the anon session is not wiped by tempchecker!
Previously, anonymous session was only being saved on subsequent requests (in `init_session()`),
causing a subtle bug that would allow session to not be inited.
Update tests to add `assert_temp_user_sesh()` to ensure that the temp user key is correctly set after anon user is inited with `/api/v1/auth/anon_user`
Other tests fix: fix test_pending to include `revisit` record counts.
> Fix anonymous session not being saved!

- webrecorder/test/test_player_proxy.py
- webrecorder/webrecorder/config/standalone_player.yaml
- webrecorder/webrecorder/models/collection.py
- webrecorder/webrecorder/models/pages.py
set coll_cdxj_ttl to -1 for player to prevent collection cdxj key from expiring
collection: check if COLL_CDXJ_TTL is >0 before calling expire()
tests: update player test to ensure collection cdxj key will not expire
> Player Fix: Ensure Collection CDXJ Never Expires in Player

- frontend/src/components/player/Webview/index.js
Adds a way to show devtools on a page in Webrecorder Player, addresses webrecorder/webrecorderplayer-electron#59
> player: add support for toggling devtools for the player webview

- docker-compose.yml
The Redis port is bound to 0.0.0.0 when running docker-compose with the given docker-compose file. From my understanding, the Webrecorder does not seem to need the Redis port to be open to function properly, so this would improve overall security on host machines without additional security measures in place.
> bind Redis to loopback interface to avoid open Redis port on host machine

- webrecorder/test/test_external.py
- webrecorder/webrecorder/apiutils.py
- webrecorder/webrecorder/uploadcontroller.py
- allow regular uploads into anon user external collections
- add /api/v1/upload and /api/v1/upload/<status> endpoints
- tests: update external api tests to include uploads
> Allow Uploading to External Anon User Collections 

- webrecorder/apps/rec.ini
- webrecorder/webrecorder/models/collection.py
- webrecorder/webrecorder/models/recording.py
- webrecorder/webrecorder/rec/main.py
- webrecorder/webrecorder/rec/storage/s3.py
- webrecorder/webrecorder/rec/storagecommitter.py
- webrecorder/webrecorder/rec/tempchecker.py
- webrecorder/webrecorder/rec/webrecrecorder.py
- webrecorder/webrecorder/rec/worker.py
- webrecorder/webrecorder/utils.py
- Making S3 commit, recording commit, cdxj download more robust
- Ensure temp lock keys always expire
- Better logging: log all file transfer ops, disable request logging for recorder
> Commit/Download IO Fixes

- webrecorder/webrecorder/autocontroller.py
- webrecorder/webrecorder/basecontroller.py
- webrecorder/webrecorder/collscontroller.py
- add require_beta_admin_access() to check for at least beta-archivist or higher user privs and admin access on collection
- wrap automation (in page and crawling) and dat features in beta access check
> beta user access control:

- webrecorder/test/test_player_proxy.py
- webrecorder/webrecorder/maincontroller.py
Serve static files by buffering directly to avoid possible unclosed file handle warnings.
Only affects CORS-requiring static files, others served by uwsgi and nginx.
> Serve static files in proxy mode directly

- webrecorder/test/test_rate_limits.py
- webrecorder/test/test_record_limits.py
- webrecorder/webrecorder/maincontroller.py
- webrecorder/webrecorder/templates/error.html
- webrecorder/webrecorder/templates/out_of_space_message.html
Updated rate limit message, ensure its being displayed for `rate_limit_exceeded` error
Also ensure out of space message is working.
Add rate limit and out of space text to unit tests, always display template for 402 errors.
> Improved Rate limit Message

- webrecorder/webrecorder/contentcontroller.py
@ikreymer has been collaborating with the [Perma.cc](https://github.com/harvard-lil/perma) team to build a version of Perma that uses the Webrecorder API for playback of web archives, and eventually, for the creation of new ones.
Perma creates collections and uploads already-existing warcs to a custom deployment of Webrecorder on behalf of visitors, and then serves the visitor a page containing an `iframe` responsible for playback. If the visitor requires a Webrecorder session cookie in order to view the playback, Webrecorder redirects the iframe in order to obtain one:
```
def redir_set_session(self):
full_path = request.environ['SCRIPT_NAME'] + request.environ['PATH_INFO']
full_path = self.add_query(full_path)
self.redir_host(None, '/_set_session?path=' + quote(full_path))
```
While …
> Option to configure session redirect host

- docker-compose.yml
Two tiny suggested tweaks to docker-compose based on the Perma team's experience so far:
We have found it convenient to run with uWSGI with the [`--need-app` flag](https://uwsgi-docs.readthedocs.io/en/latest/Options.html?highlight=%22need-app%22#need-app) so that the whole container crashes if the python application fails to load, rather than staying up but serving nothing. It's hard for me to imagine a situation in which it's anything-but-misleading for uWSGI to be running without an app; you may find this convenient as well!
We also noticed that the `proxy-certs` bind mount declaration is redundant with `./webrecorder/:/code/`. Since its presence has no effect, no particular reason to remove it from the file, except for documentation purposes. When we were just getting started, we …
> docker-compose suggestions

- webrecorder/test/test_patch.py
- webrecorder/webrecorder/config/wr.yaml
- webrecorder/webrecorder/session.py
ensure that restricted, non-anonymous session can be extended if ttl < extend time
tests: fix patch test, use httpbin instead of remote site.
Previously, 'restricted' sessions did not extend the internal session time, meaning that browsing via content domain (w/o any api calls) could still cause session to expire. This change makes it so only anonymous sessions (which are also restricted) do not extend the session, non-anonymous sessions should extend expiry (and cookie) when used.
> fix logged in session expiration from content domain usage:

- webrecorder/webrecorder/models/collection.py
- webrecorder/webrecorder/usercontroller.py
The new [`ensure_login` API route](https://github.com/webrecorder/webrecorder/blob/master/webrecorder/webrecorder/usercontroller.py#L40), if passed a collection `title`, ensures that the collection exists. However, it does not currently affect the scheduled deletion of that collection. So, collections belonging to anonymous users and external collections belonging to registered users can be deleted by `tempchecker.py` at any time, including milliseconds after `ensure_login` is called.
To prevent that unexpected behavior for registered users, this PR causes `ensure_login` to reset the TTL of the passed-in collection, using a new convenience method on the `Collection` model.
The anonymous case is not addressed by this PR.
> Mark the collection passed to `ensure_login` active

- frontend/src/components/controls/RemoteBrowserSelectUI/index.js
- frontend/src/config.js
- install-browsers.sh
- add config 'filterBrowsers' array to indicate which browsers should be included
- default to chrome:76, firefox:68, firefox:49 (for java)
- update/fix install-browsers.sh with latest chrome and firefox images, disabling pulling older versions
> filter remote browsers dropdown:

- webrecorder/webrecorder/session.py
A few dozen times a day, Perma's self-hosted instances of Webrecorder attempt to run [`Session._update_redis_and_cookie`](https://github.com/webrecorder/webrecorder/blob/master/webrecorder/webrecorder/session.py#L357) just as a given session's `ttl == 0`, which causes [this line](https://github.com/webrecorder/webrecorder/blob/master/webrecorder/webrecorder/session.py#L392) to raise `redis.exceptions.ResponseError`, since `0` is not a valid value for `SETEX`'s "seconds" argument.
This PR tweaks the existing check, `if ttl < 0: ttl = duration`, to handle `ttl == 0` as well.
Note: the exception appears to be raised by line 399 rather than 392 because of the ["redis pipeline" context manager](https://github.com/webrecorder/webrecorder/blob/master/webrecorder/webrecorder/utils.py#L124), which …
> Zero is invalid as setex "seconds" argument.

- webrecorder/webrecorder/config/wr.yaml
The description beneath "Page Detected" had the word "automatically" spelled incorrectly.
> (minor) Typo in "Page Detected" description

- init-default.sh
Double quote to prevent globbing and word splitting
> Quote variables to better support spaces, etc.

- frontend/src/components/controls/RecordURLBar/index.js
- frontend/src/components/controls/ReplayUI/index.js
- frontend/src/components/controls/ReplayUI/style.scss
- frontend/src/components/controls/ReplayURLBar/style.scss
- frontend/src/components/desktop/Webview/index.js
- frontend/src/components/player/PlayerNavUI/index.js
- frontend/src/components/player/PlayerNavUI/style.scss
- frontend/src/components/siteComponents/AppHeaderUI/index.js
- frontend/src/components/siteComponents/AppHeaderUI/style.scss
- frontend/src/containers/AppHeader/AppHeader.js
- frontend/src/containers/Patch/Patch.js
- frontend/src/containers/PlayerNav/index.js
- frontend/src/containers/Record/Record.js
- frontend/src/containers/Replay/Replay.js
- Move nav bar from app/player header to be next to location bar.
- Consistent both in desktop app and player
- Nav buttons reset when webview is initialized.
- Ensure autopilot apis not called in replay mode (eg. in player)
- Make location bar corners rounded
> Desktop Apps Nav Bar Update

- webrecorder/test/test_api_user_login.py
- webrecorder/webrecorder/admincontroller.py
- webrecorder/webrecorder/apiutils.py
- webrecorder/webrecorder/autocontroller.py
- webrecorder/webrecorder/behaviormgr.py
- webrecorder/webrecorder/bugreportcontroller.py
- webrecorder/webrecorder/collscontroller.py
- webrecorder/webrecorder/contentcontroller.py
- webrecorder/webrecorder/downloadcontroller.py
- webrecorder/webrecorder/listscontroller.py
- webrecorder/webrecorder/maincontroller.py
- webrecorder/webrecorder/models/usermanager.py
- webrecorder/webrecorder/recscontroller.py
- webrecorder/webrecorder/uploadcontroller.py
- webrecorder/webrecorder/usercontroller.py
documented the wasapi api in WR's open api spec fixes #750 
- the /api/v1 endpoint is now two endpoints serving the spec as json or yaml
- ensured that the tags set via wr_api_spec.set_curr_tag in the init_routes method of a controller are isolated to that part of the api
- added open api tags for WASAPI, Automation, and Behaviors and ensured that those routes are tagged appropriately
- added test for the /api/via/download/webdata endpoint
- added ability to mark query params as optional when defining the spec for a route
> WASAPI Open API Spec Documentation

- webrecorder/test/test_api_user_login.py
- webrecorder/test/test_register_migrate.py
- webrecorder/test/test_storage_commit.py
- webrecorder/webrecorder/apiutils.py
- webrecorder/webrecorder/downloadcontroller.py
- webrecorder/webrecorder/rec/storage/s3.py
To avoid confusion about active WARCs not being included, include them as well
- If recording is active, set `is_active` to true.. This means a WARC *may* change in the future.
- If recording is active and there is pending traffic, eg. video being downloaded, change WARC extension to `.warc.gz.open` to indicate the WARC *will* change once the pending request lands.
Checksums for open WARCs will likely change as well, so they shouldn't yet be used, but indicate the latest content available.
Also, for S3, use `s3etag` if custom S3 etag, and plain `md5` if etag is really just an md5
> WASAPI Include 'open' WARCs

- docker-compose.yml
- frontend/package.json
- frontend/src/components/controls/RemoteBrowserUI/index.js
- install-browsers.sh
Update to latest shepherd system, including support for turn server for WebRTC to ensure audio works on restricted networks. (Full WebRTC available but not enabled)
> Shepherd 1.2 Update
