Rhizome-Conifer/conifer

init-default.sh

http://unix.stackexchange.com/a/92907

GNU portability for sed

---

webrecorder/static/recordings.js
webrecorder/static/styles.css
webrecorder/templates/add_to_recording_button.html
webrecorder/templates/collection_info.html
webrecorder/templates/collection_info_buttons.html
webrecorder/templates/recording_info.html
webrecorder/templates/recordings/browse.html
webrecorder/templates/recordings/patch.html
webrecorder/templates/recordings/recorder.html
webrecorder/templates/recordings_table_actions.html

This includes
- 'add to recording' button in recordings table
- 'patch page' button when browsing 
- in recording table, open pages on row click
closes #54

Add to recording and Patch recording

---

webrecorder/static/recordings.js
webrecorder/static/styles.css
webrecorder/templates/collection_info.html
webrecorder/templates/frame_insert.html
webrecorder/templates/recording_info.html
webrecorder/templates/recordings/in_progress.html
webrecorder/templates/recordings/patch.html
webrecorder/templates/recordings/replay.html

Recorder improvements bugfixes

---

webrecorder/static/recordings.js
webrecorder/templates/content_error.html
webrecorder/templates/recording_info.html
webrecorder/templates/recordings_table_actions.html
webrecorder/test/test_recs_api.py
webrecorder/webrecorder/recscontroller.py
webrecorder/webrecorder/redisman.py

- group pages by url+ts
- ensure any page added maps to actual recorded url
- ensure any page added has a timestamp
- use new pywb postMessage url change updates
- support page removal/hiding, #120

pages work:

---

rec/wrrecorder/storagecommitter.py
rec/wrrecorder/webrecrecorder.py
webrecorder/test/test_all_register_migrate.py
webrecorder/test/test_all_temp_content.py
webrecorder/test/test_colls_api.py
webrecorder/test/test_recs_api.py
webrecorder/test/testutils.py
webrecorder/webrecorder/collscontroller.py
webrecorder/webrecorder/logincontroller.py
webrecorder/webrecorder/recscontroller.py
webrecorder/webrecorder/redisman.py
wr.yaml

Flat hierarchy per user.. allow collections and recording renaming.

Storage rename refactor

---

webrecorder/static/collection_info.js
webrecorder/templates/collection_info.html
webrecorder/test/test_all_register_migrate.py
webrecorder/test/test_all_temp_content.py
webrecorder/webrecorder/collscontroller.py
webrecorder/webrecorder/recscontroller.py

pushState used to change url as recordings are toggled
multiple recordings can be selected via: ../coll/recA,recB

recording info: using collection page, with filters

---

webrecorder/webrecorder/redisman.py
wr_sample.env

Add mailing list removal on account deletion, additional refinements

---

webrecorder/static/automate.js
webrecorder/static/recordings.js
webrecorder/static/wrscripts.js
webrecorder/webrecorder/contentcontroller.py
webrecorder/webrecorder/redisman.py
wr.yaml

Use websockets for size/bookmarks counter updates, as well as sending cookies, bookmarks, skip request messages

Websocket status updates

---

webrecorder/admin/.gitignore
webrecorder/admin/package.json
webrecorder/admin/scripts/build.js
webrecorder/admin/src/components/Navigation/index.js
webrecorder/admin/src/components/SizeFormat/index.js
webrecorder/admin/src/config.js
webrecorder/admin/src/containers/Dashboard/actions.js
webrecorder/admin/src/containers/Dashboard/index.js
webrecorder/admin/src/containers/Dashboard/reducer.js
webrecorder/admin/src/containers/Dashboard/sagas.js
webrecorder/admin/src/containers/Dashboard/style.scss
webrecorder/admin/src/containers/UserDetail/index.js
webrecorder/admin/src/containers/UserList/actions.js
webrecorder/admin/src/containers/UserList/constants.js
webrecorder/admin/src/containers/UserList/index.js
webrecorder/admin/src/containers/UserList/reducer.js
webrecorder/admin/src/containers/UserList/sagas.js
webrecorder/admin/src/routes.js
webrecorder/admin/src/utils/Api.js
webrecorder/admin/src/vars.scss
webrecorder/webrecorder/rec/webrecrecorder.py
webrecorder/webrecorder/schemas.py
webrecorder/webrecorder/usercontroller.py
wr.yaml

- Add user and temp user usage tracking with redis
- Add temp user list
- Add user and temp user usage to dashboard
- Add bundle analyzer and local settings overrides

Admin panel updates

---

webrecorder/static/collection_info.js
webrecorder/static/newrecording.js
webrecorder/templates/recordings/homepage_recorder.html
webrecorder/webrecorder/basecontroller.py
webrecorder/webrecorder/collscontroller.py

- Trim trailing whitespace on existing titles for proper table filtering
- Strip whitespace from new titles
- Update collection url matching to support multiple filters

Fixes for recording titles

---

webrecorder/admin/src/containers/UserDetail/index.js
webrecorder/webrecorder/usercontroller.py

Use GB for storage unit on admin

---

webrecorder/static/collection_info.js
webrecorder/static/edit_title_in_place.js
webrecorder/templates/bookmark_hidden_switch.html
webrecorder/templates/collection_info.html
webrecorder/templates/editable_collection_title.html
webrecorder/templates/move_collection_modal.html
webrecorder/templates/recording_card.html

- Add better escaping to recording renaming
- Use datatables cell update for proper internal cache updating (when it's visible)
closes #261, closes #272

Fixes aria and title attribute escaping, recording session filtering

---

webrecorder/templates/register.html
webrecorder/templates/val_reg.html
webrecorder/test/test_all_register_migrate.py
webrecorder/test/test_login.py
webrecorder/webrecorder/cookieguard.py
webrecorder/webrecorder/logincontroller.py

- use hidden field for registration
- use post request with cookie to validate registration
- update tests for reflect new setup

improve registration/validation to minimize fake registrations: #279

---

webrecorder/static/recordings.js
webrecorder/static/stylesheets/styles.css
webrecorder/templates/recordings/recorder.html

Update patching ui

---

README.md
init-default.sh

Update init-default.sh
Update README with new paths, update-to-date framework info.

Readme update

---

webrecorder/webrecorder/config/wr.yaml
webrecorder/webrecorder/load/main.py

- use PROXY_CACHE for regular memento mounts
- fix single mount /user/coll/<mount>/<url> access, not just /user/coll/<url>

improvement for memento mounts: (#258)

---

webrecorder/webrecorder/appcontroller.py
webrecorder/webrecorder/bugreportcontroller.py
webrecorder/webrecorder/config/wr_sample.env
webrecorder/webrecorder/gh_reporter.py
webrecorder/webrecorder/redisman.py
webrecorder/webrecorder/usercontroller.py

Add "Doesn't Look Right" bug reports as GitHub issues.

GitHub Bug Reports

---

webrecorder/webrecorder/basecontroller.py
webrecorder/webrecorder/collscontroller.py
webrecorder/webrecorder/recscontroller.py
webrecorder/webrecorder/static/collection_info.js
webrecorder/webrecorder/static/newrecording.js
webrecorder/webrecorder/templates/breadcrumbs.html

- use decodeURIComponent instead of decodeURI
- url encode coll_title
- use `-` instead of `_` for numeric recording names

Fix for new recording name

---

.gitignore
.travis.yml
appveyor.yml
webrecorder/webrecorder/standalone/assetsutils.py
webrecorder/webrecorder/standalone/hooks/hook-webrecorder.py
webrecorder/webrecorder/standalone/standalone.py

travis and appveyor: run with -v on ci

version flag: -v/--version works for standalone app via baked in config

---

webrecorder/webrecorder/static/recordings.js
webrecorder/webrecorder/static/stylesheets/styles.css
webrecorder/webrecorder/templates/mode_dropdown.html
webrecorder/webrecorder/templates/recorder.html

- Updates language from `finish` to `exit`

Combine mode selector and finish buttons

---

webrecorder/test/test_all_temp_content.py
webrecorder/test/test_login.py
webrecorder/test/test_no_invites_config.yaml
webrecorder/test/testutils.py
webrecorder/webrecorder/browsermanager.py
webrecorder/webrecorder/config/wr.yaml
webrecorder/webrecorder/contentcontroller.py
webrecorder/webrecorder/rec/webrecrecorder.py
webrecorder/webrecorder/redisman.py
webrecorder/webrecorder/static/recordings.js
webrecorder/webrecorder/websockcontroller.py

- Add support for dynamically stats about elements of a page as the page is loading
- Supported for both native and remote browsers
- Size counter for extraction includes patching
- Websocket handler optimization: (buffering messages if JSON parsing)
- Unicode fixes for extraction/patching

Dynamic Stats

---

webrecorder/webrecorder/contentcontroller.py

Add CSP header to content frame to improve security.

CSP header

---

webrecorder/test/test_all_register_migrate.py
webrecorder/webrecorder/basecontroller.py
webrecorder/webrecorder/collscontroller.py
webrecorder/webrecorder/recscontroller.py
webrecorder/webrecorder/session.py
webrecorder/webrecorder/templates/account.html
webrecorder/webrecorder/templates/confirm_delete_collection_modal.html
webrecorder/webrecorder/templates/confirm_delete_recording_modal.html
webrecorder/webrecorder/usercontroller.py

Require CSFR token on form POSTs, especially for account manipulation!

CSRF Token

---

webrecorder/webrecorder/appcontroller.py
webrecorder/webrecorder/config/wr_sample.env
webrecorder/webrecorder/static/stylesheets/footer.css
webrecorder/webrecorder/templates/footer.html

Add mailing list signup to footer

---

webrecorder/test/test_app_content_domain.py
webrecorder/test/test_extract.py
webrecorder/test/testutils.py
webrecorder/webrecorder/collscontroller.py
webrecorder/webrecorder/contentcontroller.py
webrecorder/webrecorder/session.py

- top frame, collections page only loaded from app domain
- tests: add tests to ensure content/app domain config works as expected
- session: add should_copy_cookie flag when copying cookie via set_session
- session: don't save incomplete session data to redis after using set_id(), only save cookie

content/app domain security improvements:

---

webrecorder/webrecorder/static/recordings.js
webrecorder/webrecorder/templates/utils.html

- move check for wr-archive-count element outside of patch mode
- make initial patch widget message more explicit
closes #392

Fix patch widget display of resources

---

webrecorder/test/test_all_register_migrate.py
webrecorder/webrecorder/redisman.py

- test logging in when already logged in
- test one user accessing another users public collection (200)
- test one user accessing another users' private collection (404)
redisman: fix another typo in check_read_access_public()

tests: add tests for multiple users:

---

webrecorder/test/test_all_register_migrate.py
webrecorder/webrecorder/rec/webrecrecorder.py
webrecorder/webrecorder/recscontroller.py
webrecorder/webrecorder/redisman.py

- Fixes issues with moving recording from one collection to another
- Ensure recordings have an incremented name if duplicate already exists

Recording Move Fix

---

appveyor.yml
webrecorder/test/test_cdxj_cache.py
webrecorder/test/test_cdxj_cache_config.yaml
webrecorder/test/test_rec.py
webrecorder/test/test_upload.py
webrecorder/webrecorder/fullstackrunner.py
webrecorder/webrecorder/rec/tempchecker.py

- Appveyor run tests (install prereqs, submodule, etc..)
- Fix tests to add longer waiting time
- Ensure writer is always closed
- Fix path sep

Appveyor: All Tests Pass On Windows

---

appveyor.yml
webrecorder/test/test_cdxj_cache.py
webrecorder/webrecorder/appcontroller.py
webrecorder/webrecorder/config/standalone_player.yaml
webrecorder/webrecorder/downloadcontroller.py
webrecorder/webrecorder/fullstackrunner.py
webrecorder/webrecorder/redisman.py
webrecorder/webrecorder/standalone/standalone.py
webrecorder/webrecorder/standalone/webrecorder_full.py
webrecorder/webrecorder/standalone/webrecorder_player.py
webrecorder/webrecorder/static/recordings.js
webrecorder/webrecorder/templates/content_error.html

History nav improvements:
- Url bar updated with history changes, listening to 'replace-ur' message from pywb.
- Error page listens to 'onpopstate' events and returns to original page
Player improvements:
- Player output flushes after printing port
- Player supports log level via `--loglevel` flag
- Player builds in windowed mode on Windows to avoid console
Download fix:
- Don't include any .cdxj when downloading collection/recording WARCs

Develop->Master Update

---

webrecorder/requirements.txt
webrecorder/webrecorder/contentcontroller.py
webrecorder/webrecorder/standalone/hooks/hook-webassets.py

CSP Allow WS

---

webrecorder/test/test_colls_api.py
webrecorder/test/test_rate_limits.py
webrecorder/webrecorder/contentcontroller.py
webrecorder/webrecorder/rec/webrecrecorder.py
webrecorder/webrecorder/redisman.py
webrecorder/webrecorder/templates/error.html

- rate limit applies to all users (temp and logged in), adjust message
- allow more restricted rate limit for more abusive clients, specified via RATE_LIMIT_RESTRICTED_IPS
- bin ips by class c subnet
- tests: add tests for rate limit (normal and restricted)

rate limit improvements:

---

webrecorder/test/test_player_proxy.py
webrecorder/webrecorder/browsermanager.py
webrecorder/webrecorder/config/wr.yaml
webrecorder/webrecorder/contentcontroller.py
webrecorder/webrecorder/standalone/standalone.py
webrecorder/webrecorder/standalone/webrecorder_player.py
webrecorder/webrecorder/templates/head_insert.html
webrecorder/webrecorder/websockcontroller.py

Added APIs, tests for Webrecorder Player to run in proxy mode

Player Proxy Improvements

---

webrecorder/webrecorder/collscontroller.py
webrecorder/webrecorder/redisman.py

- Return full api response for collectiond detail
- Add hash ids to bookmarks, unify them as one list

Api updates for player ui

---

webrecorder/test/test_all_temp_content.py
webrecorder/webrecorder/redisman.py

- Remove html.escape, fixes double encoding on coll_title
- Add test

Encoding fix

---

webrecorder/test/test_admin_api.py
webrecorder/test/test_anon_workflow.py
webrecorder/test/test_api_user_login.py
webrecorder/webrecorder/admincontroller.py
webrecorder/webrecorder/models/access.py
webrecorder/webrecorder/models/base.py
webrecorder/webrecorder/models/user.py
webrecorder/webrecorder/models/usermanager.py
webrecorder/webrecorder/usercontroller.py
webrecorder/webrecorder/webreccork.py

All APIs in AdminController should work, using the UserManager.
Also combined command line and API admin create user to go through same validation path
Ensure `h:defaults` created on init if doesn't exist.
Use user `desc` field for description, use `reg_data` for Cork registration info

Fix AdminController and default settings

---

webrecorder/webrecorder/appcontroller.py
webrecorder/webrecorder/static/stylesheets/styles.css
webrecorder/webrecorder/templates/footer.html
webrecorder/webrecorder/templates/howtoguide.html

Added the instructions page + link in the footer. 
Decided to call it "User Guide", since neither "Quick Start" nor "Documentation" quite work :)  
From google doc: 
[https://docs.google.com/document/d/1dlRjrHNNFkFHeKjOhM3kzYT9pZrwl3iyyBVFziRxoNs/edit#heading=h.mnarhi6uncjm](https://docs.google.com/document/d/1dlRjrHNNFkFHeKjOhM3kzYT9pZrwl3iyyBVFziRxoNs/edit#heading=h.mnarhi6uncjm)

"User Guide" 

---

webrecorder/webrecorder/static/stylesheets/styles.css
webrecorder/webrecorder/templates/howtoguide.html

Added glossary and fixed some typos. 

---

frontend/package.json
frontend/src/components/collection/CollectionDetailUI/dragLayer.js
frontend/src/components/collection/CollectionDetailUI/index.js
frontend/src/components/collection/CollectionDetailUI/rows.js
frontend/src/components/collection/CollectionDetailUI/style.scss
frontend/src/components/collection/ListsUI/ListItem.js
frontend/src/components/collection/ListsUI/index.js
frontend/src/components/collection/ListsUI/style.scss
frontend/src/config.js
frontend/src/containers/Lists/Lists.js
frontend/src/vars.scss

- Add cmd/ctrl + a to select all
- Update react-dom to 16.3.1

Adds Multi-select drag and drop 

---

webrecorder/test/test_lists_anon_user.py
webrecorder/test/test_upload.py
webrecorder/webrecorder/downloadcontroller.py
webrecorder/webrecorder/models/base.py
webrecorder/webrecorder/models/collection.py
webrecorder/webrecorder/models/importer.py
webrecorder/webrecorder/models/list_bookmarks.py
webrecorder/webrecorder/models/pages.py
webrecorder/webrecorder/models/recording.py

- Ensure new WARC download is compatible with older versions of player
- Ensure lists are serialized and imported
- When adding bookmark, verify by page_id only.

List Serialization/WARC serialization fixes

---

webrecorder/test/test_api_user_login.py
webrecorder/webrecorder/models/access.py
webrecorder/webrecorder/usercontroller.py

- Ensure users are not logged in when resetting password, not the other way around!

Reset Password fix

---

frontend/src/base.scss
frontend/src/components/HttpStatus/index.js
frontend/src/components/OutsideClick/index.js
frontend/src/components/collection/CollectionCoverUI/index.js
frontend/src/components/collection/CollectionDetailUI/dragLayer.js
frontend/src/components/collection/CollectionDetailUI/index.js
frontend/src/components/collection/CollectionListUI/index.js
frontend/src/components/collection/DeleteCollectionUI/index.js
frontend/src/components/collection/ListsUI/index.js
frontend/src/components/controls/BugReportUI/forms.js
frontend/src/components/controls/ExtractWidgetUI/index.js
frontend/src/components/controls/ModeSelectorUI/index.js
frontend/src/components/controls/NewRecordingUI/index.js
frontend/src/components/controls/PatchWidgetUI/index.js
frontend/src/components/controls/ReplayArrowButton/index.js
frontend/src/components/controls/ReplayURLBar/index.js
frontend/src/components/controls/ShareWidgetUI/index.js
frontend/src/components/siteComponents/UploadUI/index.js
frontend/src/components/siteComponents/UserManagementUI/index.js
frontend/src/components/siteComponents/UserManagementUI/loginForm.js
frontend/src/components/siteComponents/UserSettingsUI/index.js
frontend/src/components/siteComponents/UserSignup/index.js
frontend/src/containers/App/App.js
frontend/src/containers/CollectionDetail/CollectionDetail.js
frontend/src/containers/ExtractWidget/ExtractWidget.js
frontend/src/containers/Replay/Replay.js
frontend/src/containers/UserSettings/UserSettings.js
frontend/src/helpers/utils.js
frontend/src/helpers/ws.js
frontend/src/redux/selectors/index.js

- Clear client errors on navigation
- Cleanup conditional spacing
- Actually update UI during indexing for UploadUI

Style 404 page, cleanup

---

frontend/src/components/Resizable/index.js
frontend/src/components/WYSIWYG/index.js
frontend/src/components/collection/CollectionCoverUI/index.js
frontend/src/components/collection/InspectorPanelUI/index.js
frontend/src/components/collection/ListsUI/index.js
frontend/src/components/controls/RemoteBrowserUI/style.scss
frontend/src/components/controls/ReplayUI/style.scss
frontend/src/components/controls/SidebarCollectionViewerUI/index.js
frontend/src/components/controls/SidebarListViewerUI/index.js
frontend/src/components/controls/SidebarUI/index.js
frontend/src/components/siteComponents/BreadcrumbsUI/breadcrumbs.js
frontend/src/components/siteComponents/UploadUI/index.js
frontend/src/containers/Upload/Upload.js
frontend/src/redux/create.js
frontend/src/routes.js
frontend/src/shared/js/browser_controller.js

- Remote Browser treatment updates
- WYSIWYG tweaks

UI Updates

---

webrecorder/test/test_api_user_login.py
webrecorder/test/test_colls_api.py
webrecorder/webrecorder/maincontroller.py
webrecorder/webrecorder/models/access.py
webrecorder/webrecorder/models/base.py
webrecorder/webrecorder/models/user.py
webrecorder/webrecorder/models/usermanager.py

- ensure 'all_users[user]' checks that anon user exists before returning
- rename UserTable.get_user() -> UserTable.make_user()
- allow excluding superuser check from 'can_read_coll()', don't list private collections for superuser!
- tests: add tests to ensure non-existant temp user and temp user collection request result in 404

user and collection access fix:

---

frontend/src/components/collection/CollectionDetailUI/index.js
frontend/src/components/collection/CollectionFiltersUI/index.js
frontend/src/components/collection/InspectorPanelUI/index.js
frontend/src/components/controls/RemoteBrowserSelectUI/index.js
frontend/src/containers/CollectionFilters/CollectionFilters.js
frontend/src/routes.js

- Remove old bulk addition modal
- Only show temp user alert for own collection
- Remove Inspector placeholder desc from public views
- Update Remote Browser language

Fix: Remote browser patch route order, minor:

---

webrecorder/test/test_admin_api.py
webrecorder/webrecorder/admincontroller.py

- add prototype /api/v1/stats/search, /api/v1/stats/query endpoints
- stat range: fix upper bound check
- stat names: user-friendly stat names
- table stats: add 'User Table' and 'Temp Table' for logged in and temp user tables, respectively
- tests: add tests for stats endpoints

new stats api to use with grafana json api:

---

webrecorder/test/test_admin_api.py
webrecorder/webrecorder/admincontroller.py
webrecorder/webrecorder/maincontroller.py

- add temp collection move size and count stats
- add user login time series
- add session count

more stats for grafana:

---

webrecorder/test/test_admin_api.py
webrecorder/webrecorder/admincontroller.py
webrecorder/webrecorder/models/importer.py
webrecorder/webrecorder/models/list_bookmarks.py
webrecorder/webrecorder/models/user.py
webrecorder/webrecorder/webreccork.py

- Add Collection Stats
- Fix user `last_login` to consistently use UTC time.

Collection Stats

---

frontend/src/components/controls/SidebarListViewerUI/style.scss
frontend/src/components/controls/SidebarPageViewerUI/style.scss
frontend/src/components/siteComponents/UploadUI/index.js
frontend/src/redux/modules/collection.js
frontend/src/redux/modules/list.js
frontend/src/redux/modules/recordings.js
frontend/src/redux/modules/remoteBrowsers.js
frontend/src/routes.js
webrecorder/webrecorder/contentcontroller.py

- prevent double-encoded querystrings
- update create_browser to use getunicode
- update list route to support unicode slugs
- disable upload widget backdrop when upload is active

Unicode fixes, misc:

---

frontend/src/components/controls/StandaloneRecorderUI/index.js
frontend/src/components/controls/StandaloneRecorderUI/style.scss

#36 https://github.com/webrecorder/Sprints/issues/36

adds labels to dropdown on hp and switches order

---

frontend/src/components/collection/CollectionDetailUI/columns.js
frontend/src/components/collection/CollectionDetailUI/index.js

The page title is blue because it is a link, is this ok?

makes page title a link in collection view

---

webrecorder/requirements.txt
webrecorder/test/test_admin_api.py
webrecorder/test/test_anon_workflow.py
webrecorder/test/test_api_user_login.py
webrecorder/test/test_colls_api.py
webrecorder/test/test_lists_anon_user.py
webrecorder/test/test_lists_multi_user.py
webrecorder/webrecorder/admincontroller.py
webrecorder/webrecorder/apiutils.py
webrecorder/webrecorder/basecontroller.py
webrecorder/webrecorder/bugreportcontroller.py
webrecorder/webrecorder/collscontroller.py
webrecorder/webrecorder/contentcontroller.py
webrecorder/webrecorder/listscontroller.py
webrecorder/webrecorder/maincontroller.py
webrecorder/webrecorder/recscontroller.py
webrecorder/webrecorder/usercontroller.py

- first pass on adding openapi/swagger markup to webrecorder api.
- Existing APIs grouped via tags
- Input param types added.
- Some obsolete apis removed
- `/api/v1` returns openapi yaml

OpenAPI Spec (Initial Pass)

---

webrecorder/test/test_player_proxy.py
webrecorder/webrecorder/maincontroller.py
webrecorder/webrecorder/standalone/serializefakeredis.py

- check for dict type before trying to parse expiration, store as 'exp'
- always load values as tuple (value, exp) for expiring dict
- bump serializer version to 2

serializefakeredis: Fix serialization with new fakeredis _ExpiringDict

---

frontend/src/components/collection/InspectorPanelUI/index.js

don't show description header when there isn't a description (i.e. https://webrecorder.io/m4rk3r/important/list/bookmarks/b3/20170416032223/https://www.youtube.com/watch?v=uxgUjyqN7FU&t=2380s)

No description if empty

---

frontend/src/base.scss
frontend/src/components/controls/RecordingToolsUI/index.js
frontend/src/components/controls/ReplayURLBar/style.scss

Mobile replay

---

webrecorder/test/test_api_user_login.py
webrecorder/webrecorder/models/datshare.py
webrecorder/webrecorder/models/user.py
webrecorder/webrecorder/models/usermanager.py
webrecorder/webrecorder/usercontroller.py
webrecorder/webrecorder/webreccork.py

- user 'full_name' property in user for full name
- on registration validation, set 'full_name' from reg_data.name
- tests: update tests to ensure full_name set on registration is present

user full_name fix:

---

README.md
install-browsers.sh
webrecorder/webrecorder/config/wr_sample.env

- Update README, including fixes from @perricci and @m4rk3r 
- wr_sample.env update by @m4rk3r 
- remote browser info: add install-browser.sh to install all known remote browsers, add info about remote browsers to README

README and Doc Fixes

---

frontend/src/shared/js/browser_controller.js

- migrate latest version of browser_controller.js from shepherd to frontend
- trigger audio init on first click to avoid browser autoplay block

audio fix:

---

webrecorder/webrecorder/basecontroller.py
webrecorder/webrecorder/contentcontroller.py
webrecorder/webrecorder/maincontroller.py

- use REQUEST_URI if available to ensure unaltered url is used for content replay
- error handling: always display html error page for errors coming from content domain

content handling improvements:

---

webrecorder/Dockerfile
webrecorder/test/test_anon_workflow.py
webrecorder/webrecorder/basecontroller.py
webrecorder/webrecorder/config/assets.yaml
webrecorder/webrecorder/contentcontroller.py
webrecorder/webrecorder/maincontroller.py
webrecorder/webrecorder/templates/head_insert.html

Includes changes for pywb from webrecorder/pywb#379:
- New wombatProxyMode.js and autoFetchWorkerProxyMode.js added
- update head_insert.html
- /static_cors/ for auto-fetch worker cors loading
- switch default Docker image to pywb:develop
- tests: fix tests related to different spacing when pywb using ujson
Not yet included:
- /proxy-fetch/ path occasionally used by auto-fetch worker (not yet needed for existing browsers)

Update for pywb change

---

frontend/src/components/siteComponents/Footer/index.js
frontend/src/containers/RegisterAccount/RegisterAccount.js
frontend/src/containers/RegisterAccount/style.scss
frontend/src/routes.js

- Add success page, remove redirect to homepage

Update registration flow UI

---

frontend/src/components/siteComponents/Footer/index.js
frontend/src/containers/RegisterAccount/RegisterAccount.js
frontend/src/containers/RegisterAccount/style.scss
frontend/src/routes.js
webrecorder/test/test_api_user_login.py
webrecorder/test/test_register_migrate.py
webrecorder/webrecorder/models/usermanager.py
webrecorder/webrecorder/templates/emailconfirm.html
webrecorder/webrecorder/usercontroller.py
webrecorder/webrecorder/webreccork.py

Validation system improvements:
- Include `?username=<...>` in email validation link to support checking if already registered.
- Provide already registered error info instead of more generic error.
- Don't auto-redirect but confirm when validation succeeds

Email Validation Improvements

---

frontend/src/components/player/PlayerNavUI/index.js
frontend/src/components/player/PlayerNavUI/style.scss

- Prevent back arrow navigating to landing page after loading a warc
- Add margin to navigation arrows

Minor fixes:

---

frontend/src/components/player/PlayerNavUI/style.scss
frontend/src/helpers/utils.js

- remoteBrowserMod for player use ts or '', fixes `null` appearance
- don't override outline on nav buttons

Player fixes

---

frontend/src/components/EmbedFooter/style.scss
frontend/src/components/player/Help/index.js
frontend/src/containers/Indexing/index.js
frontend/src/containers/Indexing/style.scss
frontend/src/containers/Landing/style.scss
webrecorder/requirements.txt

Add a "Additional Info" message if player indexing stalls at 100% to allow user to view any errors.

V1.6.2 - Stalled Indexing message

---

frontend/src/components/siteComponents/UserSignup/index.js

- fixes occasional issue where missing confirmation password would prevent submitting signup form

Add missingPw flag check on update, confirm valid email before submission

---

frontend/src/components/collection/CollectionDetailUI/rows.js
frontend/src/components/collection/ListsUI/index.js
frontend/src/helpers/utils.js
frontend/src/redux/modules/list.js

Preserve custom bookmark fields when moving bookmarks between lists

---

webrecorder/webrecorder/models/access.py
webrecorder/webrecorder/models/base.py
webrecorder/webrecorder/models/collection.py
webrecorder/webrecorder/models/importer.py
webrecorder/webrecorder/models/pages.py
webrecorder/webrecorder/models/recording.py
webrecorder/webrecorder/rec/storage/__init__.py
webrecorder/webrecorder/rec/storage/base.py
webrecorder/webrecorder/rec/storage/local.py
webrecorder/webrecorder/rec/storage/s3.py
webrecorder/webrecorder/rec/storage/storagepaths.py

New branch without the changes introduced in od_upstream, but containing all the docstrings I inserted up until now.

added docstrings

---

webrecorder/webrecorder/admin.py
webrecorder/webrecorder/models/usermanager.py

Added listing of existing users and check if given username exists to command-line administrative tool.

added to administrative tool

---

.travis.yml

Update OSX build to to Xcode 8 as Xcode 6.4 is deprecated.
Will also change WR Player minimum to OSX 10.11 from OSX 10.10

Build: Travis OSX update

---

webrecorder/test/test_admin_api.py
webrecorder/webrecorder/admincontroller.py
webrecorder/webrecorder/rec/storagecommitter.py

Add timeseries for:
- User created by date
- Collection count updated by date
- Collection size updated by date

Stats: Additional Stats API for Grafana

---

webrecorder/test/test_upload.py
webrecorder/webrecorder/standalone/webrecorder_player.py

- ensure user 'local' and collection 'collection' exist for cache to be considered valid
- ensure the local browser key (up:127.0.0.1) is re-inited even when loading from cache, to support old versions with different key (ip:127.0.0.1)

player init: more robust cache load:

---

webrecorder/webrecorder/rec/tempchecker.py

While investigating (non-fatal) error messages thrown during session cleanup yesterday, I started adding comments for myself to `tempchecker.py`, and started making try/excepts narrower to make sure I understood which errors were being thrown where.
These commits are the results of my internal note-taking/experimenting. I thought I'd offer it as a PR in case it might be helpful to others.
Please feel free to simply close this entire PR: no pressure to accept any of it, much less all of it.

Inconsequential tweaks from studying `tempchecker.py`

---

frontend/package.json
frontend/src/routes.js
webrecorder/webrecorder/models/user.py

- backend: update role check (from production)
- frontend: update prod build
- frontend: update route order, ensure 'live' route before more general replay routes

misc fixes:

---

frontend/src/components/player/Help/index.js
frontend/src/components/siteComponents/DesktopSettingsUI/index.js
frontend/src/helpers/utils.js

Add Flash to version stack display

player/desktop version stack: include flash version in stack display

---

frontend/src/containers/Home/Home.js
frontend/src/helpers/utils.js

- fix insert typo in home.js
- use forEach instead of for to adhere to style

typos/style fix:

---

frontend/babel.config.js
frontend/package.json
frontend/src/components/siteComponents/ApiDocs/index.js
frontend/src/components/siteComponents/ApiDocs/style.scss
frontend/src/components/siteComponents/Documentation/index.js
frontend/src/components/siteComponents/index.js
frontend/src/routes.js
frontend/webpack/webpack.config.client.development.js
frontend/yarn.lock
webrecorder/test/test_api_user_login.py
webrecorder/webrecorder/apiutils.py
webrecorder/webrecorder/contentcontroller.py
webrecorder/webrecorder/downloadcontroller.py
webrecorder/webrecorder/maincontroller.py

Swagger UI at `/docs/api` + API text tweaks

Swagger UI

---

README.md
frontend/src/components/siteComponents/AppHeaderUI/index.js
frontend/src/components/siteComponents/HomeUI/index.js
frontend/src/components/siteComponents/HomeUI/style.scss
frontend/src/components/siteComponents/HomepageAnnouncement/index.js
frontend/src/components/siteComponents/HomepageAnnouncement/style.scss
webrecorder/webrecorder/config/wr_sample.env

- Set `ANON_DISABLED=true` in `wr_sample.env`
- Update readme with Desktop App, anon changes
- small home page tweaks

Home page and readme updates

---

frontend/src/containers/RegisterAccount/RegisterAccount.js
frontend/src/containers/RegisterAccount/style.scss
frontend/src/routes.js

Add an additional user action step in account verification to prevent erroneous email client link-prefetching or otherwise invalidated registrations.

Add user action to email verification page
